modLoader="javafml" 
loaderVersion="[40,)"
#issueTrackerURL=""
license="MIT"

[[mods]] 
modId="mightyarchitect"
version="0.7"
displayName="The Mighty Architect" 
#updateJSONURL=""
authors="simibubi" 
description='''Design elaborate buildings within a minute! [G] is the default keybind for getting started. Check out the wiki for more info.'''

[[dependencies.mightyarchitect]] 
    modId="forge"
    mandatory=true 
    versionRange="[40,)"
    ordering="NONE"
    side="CLIENT"
	
[[dependencies.mightyarchitect]] 
    modId="forge"
    mandatory=true 
    versionRange="[40,)"
    ordering="NONE"
    side="SERVER"

[[dependencies.mightyarchitect]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.18.2]"
    ordering="NONE"
    side="BOTH"